# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Home Page of Jason E. Miller, Ph.D.
email: jason.miller@csuci.edu
description: >- # this means to ignore newlines until "baseurl:"
  This is the web home for Prof. Jason E. Miller, containing links and information relating 
  to professional intersts.  All content on this site represents the personal and professional 
  opinions of the author alone, and they are not meant to represent those of California State 
  University Channel Islands or its associated legal entities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jasonemiller.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jasonemiller
github_username: jasonemiller

# Build settings
theme: minima
plugins:
  - jekyll-feed

# from https://github.com/jekyll/minima/blob/master/README.md, 'Customize navigation Links'
header_pages:
  - teaching.md
  - research.md
  - links.md
  - about.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
